package com.nishant.ragassistant.service;

import org.springframework.ai.document.Document;
import org.springframework.ai.reader.tika.TikaDocumentReader;
import org.springframework.ai.transformer.splitter.TokenTextSplitter;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * PHASE 1 (original): called directly and synchronously from the upload
 * endpoint - the HTTP request blocked until parsing + chunking + embedding
 * finished, and this class generated its own documentId internally.
 *
 * PHASE 2 (current): this class no longer knows or cares whether it's being
 * called synchronously or from a Kafka consumer - that's the point of good
 * separation. What changed: documentId is now passed IN rather than
 * generated here, because the controller needs the ID immediately (before
 * ingestion even starts) so it can return it to the client and track status
 * against it. See IngestionConsumer for who calls this now.
 */
@Service
public class IngestionService {

    private final VectorStore vectorStore;

    public IngestionService(VectorStore vectorStore) {
        this.vectorStore = vectorStore;
    }

    public record IngestResult(String documentId, int chunkCount) {}

    /**
     * Reads a document, splits it into chunks, embeds each chunk, and stores
     * it in pgvector. Returns the document ID and number of chunks created.
     *
     * WHAT'S HAPPENING UNDER THE HOOD:
     *   1. TikaDocumentReader extracts raw text from PDF/DOCX/TXT/etc.
     *   2. TokenTextSplitter breaks that text into token-sized chunks
     *      (not character-sized - this matters because the embedding model
     *      has a token limit, not a character limit).
     *   3. vectorStore.add(chunks) - Spring AI automatically calls the
     *      configured embedding model (nomic-embed-text via Ollama) for
     *      each chunk, then stores the resulting vector + original text
     *      + metadata in the Postgres `vector_store` table.
     *
     * @param documentId generated by the caller (controller, at upload time) -
     *                    not generated in here anymore, see class javadoc.
     */
    public IngestResult ingest(Resource file, String originalFilename, String documentId) {
        // Step 1: extract text
        TikaDocumentReader reader = new TikaDocumentReader(file);
        List<Document> rawDocuments = reader.get();

        // Step 2: chunk it. Defaults: ~800 tokens per chunk, some overlap between
        // chunks so a fact sitting on a chunk boundary isn't lost entirely.
        // Tune these once you see how retrieval quality behaves on your real documents.
        TokenTextSplitter splitter = new TokenTextSplitter();
        List<Document> chunks = splitter.apply(rawDocuments);

        // Step 3: attach metadata so we can cite sources later and trace
        // every chunk back to the document it came from.
        chunks.forEach(chunk -> {
            chunk.getMetadata().put("documentId", documentId);
            chunk.getMetadata().put("filename", originalFilename);
        });

        // Step 4: embed + store. This is the line that actually calls the
        // embedding model - one call per chunk (or batched, depending on
        // the provider). This is the slow part that justified making
        // ingestion asynchronous - it now runs inside IngestionConsumer,
        // off the HTTP request thread entirely.
        vectorStore.add(chunks);

        return new IngestResult(documentId, chunks.size());
    }
}

